"""empty message

Revision ID: 681078a337d1
Revises: b0f66f5535dc
Create Date: 2017-09-28 15:49:38.991354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681078a337d1'
down_revision = 'b0f66f5535dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('detailed_description', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('expected_outcomes', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('gender_approach', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('innovation', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('project_activities', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('project_budget', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'project_budget')
    op.drop_column('applications', 'project_activities')
    op.drop_column('applications', 'innovation')
    op.drop_column('applications', 'gender_approach')
    op.drop_column('applications', 'expected_outcomes')
    op.drop_column('applications', 'detailed_description')
    # ### end Alembic commands ###
