"""empty message

Revision ID: 765d276b70c9
Revises: df19b99fdd6c
Create Date: 2017-09-28 15:37:06.479490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765d276b70c9'
down_revision = 'df19b99fdd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('contact_person', sa.JSON(), nullable=False))
    op.add_column('applications', sa.Column('relevant_interests', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('self_government', sa.String(length=500), nullable=False))
    op.add_column('applications', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'title')
    op.drop_column('applications', 'self_government')
    op.drop_column('applications', 'relevant_interests')
    op.drop_column('applications', 'contact_person')
    # ### end Alembic commands ###
