"""empty message

Revision ID: b0f66f5535dc
Revises: b64bb1f3f5b8
Create Date: 2017-09-28 15:48:48.922144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f66f5535dc'
down_revision = 'b64bb1f3f5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('other_applicants', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('project_summaries', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'project_summaries')
    op.drop_column('applications', 'other_applicants')
    # ### end Alembic commands ###
